# Generated by Django 4.2.4 on 2025-04-23 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_societies', to=settings.AUTH_USER_MODEL),
        ),
    ]
