# Generated by Django 5.1.6 on 2025-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('community', 'Community'), ('club', 'Club'), ('society', 'Society')], default='public', max_length=20),
        ),
    ]
