# Generated by Django 4.2.4 on 2025-04-16 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_interest_community_is_approved_event_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='society',
            name='event_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='interests',
            field=models.ManyToManyField(related_name='societies', to='student_management.interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_name',
            field=models.CharField(max_length=100),
        ),
    ]
