# Generated by Django 4.2.4 on 2025-04-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_remove_notification_title_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='can_book',
            field=models.BooleanField(default=True),
        ),
    ]
