# Generated by Django 5.1.6 on 2025-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_eventdetails_can_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
