# Generated by Django 5.1.6 on 2025-04-29 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_event_maximum_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
